# 📘 Notebook – Tabela 1

**Acesso aos exames preventivos de saúde (PNS 2013 e 2019)**
Mulheres com 25 anos ou mais

In [13]:
import pandas as pd
import numpy as np
import sys
from pathlib import Path

# Setup do ambiente
sys.path.append(str(Path("..").resolve()))
from service.pns_service import (
    get_dataframe,
    list_variables,
    register_derived_variable
)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

## 🔹 Célula 2 – Inspeção das variáveis disponíveis (bronze)

Objetivo: confirmar **empiricamente** quais variáveis existem para exames preventivos.

In [14]:
df_vars = list_variables()

df_vars[df_vars["variable"].str.contains(
    "preventivo|mamografia", case=False, na=False
)]

,variable,descricao,categoria,tipo_dado,regra_derivacao,depends_on,code_2013,type_2013,exists_2013,code_2019,type_2019,exists_2019
7,mamografia_paga,A Sra pagou algum valor pela última mamografia...,fisica,string,None,None,R019,string,True,R019,string,True
8,mamografia_plano,A última mamografia foi coberta por plano de s...,fisica,string,None,None,R018,string,True,None,string,False
9,mamografia_quando,\n Quando foi a última vez que a Sra fe...,fisica,string,None,None,R017,string,True,R01701,string,True
10,mamografia_sus,A última mamografia foi feita pelo SUS? (1=Sim...,fisica,string,None,None,R020,string,True,R020,string,True
12,preventivo_pago,A Sra pagou algum valor pelo último exame prev...,fisica,string,None,None,R004,string,True,R004,string,True
13,preventivo_plano,O último exame preventivo foi coberto por plan...,fisica,string,None,None,R003,string,True,None,string,False
14,preventivo_quando,\n Quando foi a última vez que a Sra fe...,fisica,string,None,None,R001,string,True,R00101,string,True
15,preventivo_sus,O último exame preventivo foi feito pelo SUS? ...,fisica,string,None,None,R005,string,True,R005,string,True

## 🔹 Célula 3 – Carregamento mínimo para inspeção empírica

Objetivo: **ver os valores reais**, sem ainda criar nenhuma variável analítica.

In [15]:
variables = [
    "preventivo_quando",
    "mamografia_quando"
]

sources = ["2013", "2019"]

df_raw = get_dataframe(
    variables=variables,
    sources=sources
)

df_raw.head()

    id_upa id_morador id_domicilio preventivo_quando mamografia_quando origem
0  1100001          1         0001                 2              None   2013
1  1100001          1         0002                 5              None   2013
2  1100001          2         0003                 3              None   2013
3  1100001          1         0009                 2              None   2013
4  1100001          2         0010              None              None   2013

## 🔹 Célula 4 – Conferência estrutural e de domínio (obrigatória)

In [16]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158910 entries, 0 to 158909
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id_upa             158910 non-null  object
 1   id_morador         158910 non-null  object
 2   id_domicilio       158910 non-null  object
 3   preventivo_quando  72514 non-null   object
 4   mamografia_quando  33476 non-null   object
 5   origem             158910 non-null  object
dtypes: object(6)
memory usage: 7.3+ MB

In [17]:
for col in variables:
    print(f"\nDistribuição de valores em '{col}':")
    print(df_raw[col].value_counts(dropna=False))

Distribuição de valores em 'preventivo_quando':
preventivo_quando
None    86396
1       30539
2       16630
4       12121
5        6799
3        6425
Name: count, dtype: int64

Distribuição de valores em 'mamografia_quando':
mamografia_quando
None    125434
1        17325
2         7970
4         5151
3         3030
Name: count, dtype: int64

📌 **Conclusão empírica (documentada):**

* Valores `"1"`, `"2"`, `"3"`, `"4"` indicam que o exame foi realizado;
* Qualquer outro valor (`None`, `"5"`, etc.) indica que **não foi realizado**;
* A regra é **simétrica e válida para ambos os exames**.

## 🔹 Célula 5 – Registro das variáveis GOLD (persistentes)

Aqui formalizamos a regra analítica como **variáveis derivadas persistidas** no SQLite.

In [18]:
RANGE_FEZ = ["1", "2", "3", "4"]

register_derived_variable(
    name="preventivo_fez",
    description=(
        "Indicador (0/1) se a mulher realizou exame preventivo "
        "(papanicolau). Assume 1 quando preventivo_quando ∈ {1,2,3,4}, "
        "e 0 caso contrário."
    ),
    depends_on=["preventivo_quando"],
    func=lambda df: df["preventivo_quando"].isin(RANGE_FEZ).astype(int)
)

register_derived_variable(
    name="mamografia_fez",
    description=(
        "Indicador (0/1) se a mulher realizou exame de mamografia. "
        "Assume 1 quando mamografia_quando ∈ {1,2,3,4}, "
        "e 0 caso contrário."
    ),
    depends_on=["mamografia_quando"],
    func=lambda df: df["mamografia_quando"].isin(RANGE_FEZ).astype(int)
)

📌 Essas variáveis passam a compor o **nível gold**:

* documentadas no catálogo;
* persistidas no banco;
* reutilizáveis em qualquer notebook futuro.

## 🔹 Célula 6 – Forçar cálculo e persistência no SQLite

In [19]:
df_gold = get_dataframe(
    variables=["preventivo_fez", "mamografia_fez"],
    sources=["2013", "2019"]
)

df_gold.head()

    id_upa id_morador  preventivo_fez id_domicilio origem  mamografia_fez
0  1100001          1               1         0001   2013               0
1  1100001          1               0         0002   2013               0
2  1100001          2               1         0003   2013               0
3  1100001          1               1         0009   2013               0
4  1100001          2               0         0010   2013               0

## 🔹 Célula 7 – Validação empírica das variáveis gold

In [20]:
print("preventivo_fez:")
print(df_gold["preventivo_fez"].value_counts(dropna=False))

print("\nmamografia_fez:")
print(df_gold["mamografia_fez"].value_counts(dropna=False))

preventivo_fez:
preventivo_fez
0    93195
1    65715
Name: count, dtype: int64

mamografia_fez:
mamografia_fez
0    125434
1     33476
Name: count, dtype: int64

## 🔹 Célula 8 – Função auxiliar para cálculo da Tabela 1

In [21]:
def tabela_acesso(df, col):
    fez = (df[col].mean() * 100).round(2)
    nao_fez = (100 - fez).round(2)
    return pd.Series(
        [fez, nao_fez, 100.0],
        index=["Fez", "Não fez", "Total"]
    )

## 🔹 Célula 9 – Construção da Tabela 1 (por ano)

In [22]:
tabelas = {}

for ano in sorted(df_gold["origem"].unique()):
    df_ano = df_gold[df_gold["origem"] == ano]
    
    tabela = pd.DataFrame({
        "Papanicolau": tabela_acesso(df_ano, "preventivo_fez"),
        "Mamografia": tabela_acesso(df_ano, "mamografia_fez")
    })
    
    tabelas[ano] = tabela

## 🔹 Célula 10 – Exibição final (formato artigo)

In [23]:
for ano, tabela in tabelas.items():
    print(f"\nTabela 1 – Acesso aos serviços preventivos (%), PNS {ano}")
    display(tabela)

Tabela 1 – Acesso aos serviços preventivos (%), PNS 2013

         Papanicolau  Mamografia
Fez            41.33       19.49
Não fez        58.67       80.51
Total         100.00      100.00

Tabela 1 – Acesso aos serviços preventivos (%), PNS 2019

         Papanicolau  Mamografia
Fez            41.37       22.14
Não fez        58.63       77.86
Total         100.00      100.00